name: vk_bridge
description: A dart package for working with VK Mini Apps via VK Bridge. Works web, mobile-web
homepage: https://github.com/optimist-dev/vk_bridge
version: 2.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3
  built_value: ^8.1.3
  built_collection: ^5.1.1
  rxdart: ^0.27.2
  meta: ^1.7.0

dev_dependencies:
  test: '>=1.16.0 <2.0.0'
  build_runner: ^2.1.5
  built_value_generator: ^8.1.3
