name: vk_bridge

version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  js: ^0.6.2
  built_value: ^7.1.0
  rxdart: ^0.24.1

dev_dependencies:
  test: '>=1.15.0 <2.0.0'
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
